import { Alert, Aggregate, FlaggedRequest } from "@/types";

export const mockFlaggedRequests: FlaggedRequest[] = [
  {
    id: "req_7d3f_1",
    ts: "2025-09-30T11:43:00Z",
    channel: "chat",
    region: "Eastern Province",
    text_preview: "قلق شديد بسبب نتائج الاختبارات، لا أستطيع النوم منذ أيام وأشعر بضغط كبير",
    urgency: "HIGH",
    confidence: 0.89,
    category: "exam_stress",
    emotion: "distress",
    status: "pending",
  },
  {
    id: "req_7d3f_2",
    ts: "2025-09-30T11:41:00Z",
    channel: "chat",
    region: "Eastern Province",
    text_preview: "تأخر الرد كثير وأنا بحاجة لمساعدة عاجلة، الوضع صعب جداً",
    urgency: "HIGH",
    confidence: 0.84,
    category: "wait_times",
    emotion: "distress",
    status: "pending",
  },
  {
    id: "req_9k1a_1",
    ts: "2025-09-30T11:40:00Z",
    channel: "call",
    region: "Riyadh",
    text_preview: "انتظار طويل جداً، ما في رد من الموظفين، مشغولين دائماً",
    urgency: "MEDIUM",
    confidence: 0.77,
    category: "wait_times",
    emotion: "anger",
    status: "pending",
  },
  {
    id: "req_9k1a_2",
    ts: "2025-09-30T11:38:00Z",
    channel: "call",
    region: "Riyadh",
    text_preview: "ما عندي معلومات عن كيف أحجز موعد، والموقع مو واضح",
    urgency: "MEDIUM",
    confidence: 0.72,
    category: "eligibility_confusion",
    emotion: "sadness",
    status: "pending",
  },
  {
    id: "req_3x2b_1",
    ts: "2025-09-30T10:15:00Z",
    channel: "call",
    region: "Makkah",
    text_preview: "زحمة كبيرة ووقت طويل، ليش التأخير هذا؟",
    urgency: "MEDIUM",
    confidence: 0.68,
    category: "wait_times",
    emotion: "anger",
    status: "pending",
  },
  {
    id: "req_tab_1",
    ts: "2025-09-30T11:30:00Z",
    channel: "chat",
    region: "Tabuk",
    text_preview: "أحتاج استشارة عامة عن الخدمات المتوفرة",
    urgency: "LOW",
    confidence: 0.45,
    category: "general_inquiry",
    emotion: "calm",
    status: "pending",
  },
  {
    id: "req_tab_2",
    ts: "2025-09-30T11:25:00Z",
    channel: "call",
    region: "Tabuk",
    text_preview: "متابعة على طلب سابق، متى بيكون الموعد؟",
    urgency: "LOW",
    confidence: 0.52,
    category: "follow_up",
    emotion: "calm",
    status: "pending",
  },
];

export const mockAlerts: Alert[] = [
  {
    id: "alrt_7d3f",
    ts: "2025-09-30T11:50:00Z",
    region: "Eastern Province",
    summary: "Distress spike (+2.6σ) tied to exam_stress in chat",
    evidence: {
      window: "last_45m",
      z_scores: { distress: 2.6, neg_sentiment: 2.1 },
      top_phrases: ["نتائج الاختبارات", "قلق", "تأخير الرد"],
      flagged_count: 15,
    },
    recommendations: [
      {
        type: "staffing",
        text: "Shift +2 agents to chat queue in Eastern Province for 3h",
      },
      {
        type: "messaging",
        text: "Add IVR/chat quick-reply for exam stress resources",
      },
    ],
    status: "pending",
    confidence: 0.81,
  },
  {
    id: "alrt_9k1a",
    ts: "2025-09-30T11:40:00Z",
    region: "Riyadh",
    summary: "Negative sentiment + wait_times complaints (+3.1σ) in calls",
    evidence: {
      window: "last_30m",
      z_scores: { neg_sentiment: 3.1 },
      top_phrases: ["انتظار طويل", "ما في رد", "مشغول"],
      flagged_count: 12,
    },
    recommendations: [
      {
        type: "routing",
        text: "Temporarily prioritize call queue A > B for 60m",
      },
      {
        type: "staffing",
        text: "Move +1 agent from survey callbacks to call queue",
      },
    ],
    status: "pending",
    confidence: 0.77,
  },
  {
    id: "alrt_3x2b",
    ts: "2025-09-30T10:15:00Z",
    region: "Makkah",
    summary: "Elevated anger during peak hours in call channel",
    evidence: {
      window: "last_60m",
      z_scores: { anger: 2.3, neg_sentiment: 1.9 },
      top_phrases: ["زحمة", "وقت طويل", "ليش التأخير"],
      flagged_count: 8,
    },
    recommendations: [
      {
        type: "staffing",
        text: "Add +1 senior counselor to call queue during 10-12pm window",
      },
    ],
    status: "approved",
    confidence: 0.73,
  },
];

export const mockAggregates: Record<string, Aggregate> = {
  "Eastern Province": {
    window: "last_60m",
    region: "Eastern Province",
    counts: { events: 312, calls: 180, chats: 120, surveys: 12 },
    sentiment_pct: { pos: 0.18, neu: 0.29, neg: 0.53 },
    emotions_pct: { distress: 0.41, anger: 0.17, sadness: 0.22, calm: 0.2 },
    top_topics: [
      { key: "exam_stress", pct: 0.26 },
      { key: "wait_times", pct: 0.19 },
      { key: "eligibility_confusion", pct: 0.12 },
    ],
    ewi: 0.68,
    anomalies: [
      { metric: "distress", z: 2.6 },
      { metric: "neg_sentiment", z: 2.2 },
    ],
  },
  Qassim: {
    window: "last_60m",
    region: "Qassim",
    counts: { events: 198, calls: 134, chats: 52, surveys: 12 },
    sentiment_pct: { pos: 0.32, neu: 0.43, neg: 0.25 },
    emotions_pct: { distress: 0.23, anger: 0.15, sadness: 0.14, calm: 0.48 },
    top_topics: [
      { key: "wait_times", pct: 0.21 },
      { key: "appointment_booking", pct: 0.19 },
      { key: "general_inquiry", pct: 0.17 },
    ],
    ewi: 0.45,
    anomalies: [],
  },
  Riyadh: {
    window: "last_60m",
    region: "Riyadh",
    counts: { events: 487, calls: 320, chats: 145, surveys: 22 },
    sentiment_pct: { pos: 0.22, neu: 0.35, neg: 0.43 },
    emotions_pct: { distress: 0.32, anger: 0.21, sadness: 0.18, calm: 0.29 },
    top_topics: [
      { key: "wait_times", pct: 0.31 },
      { key: "appointment_booking", pct: 0.19 },
      { key: "medication_queries", pct: 0.14 },
    ],
    ewi: 0.62,
    anomalies: [{ metric: "neg_sentiment", z: 3.1 }],
  },
  Makkah: {
    window: "last_60m",
    region: "Makkah",
    counts: { events: 256, calls: 198, chats: 48, surveys: 10 },
    sentiment_pct: { pos: 0.34, neu: 0.41, neg: 0.25 },
    emotions_pct: { distress: 0.24, anger: 0.18, sadness: 0.12, calm: 0.46 },
    top_topics: [
      { key: "family_support", pct: 0.22 },
      { key: "general_inquiry", pct: 0.18 },
      { key: "wait_times", pct: 0.15 },
    ],
    ewi: 0.42,
    anomalies: [],
  },
  Madinah: {
    window: "last_60m",
    region: "Madinah",
    counts: { events: 143, calls: 98, chats: 38, surveys: 7 },
    sentiment_pct: { pos: 0.41, neu: 0.38, neg: 0.21 },
    emotions_pct: { distress: 0.19, anger: 0.11, sadness: 0.14, calm: 0.56 },
    top_topics: [
      { key: "general_inquiry", pct: 0.28 },
      { key: "resource_request", pct: 0.17 },
      { key: "follow_up", pct: 0.12 },
    ],
    ewi: 0.35,
    anomalies: [],
  },
  Asir: {
    window: "last_60m",
    region: "Asir",
    counts: { events: 178, calls: 112, chats: 54, surveys: 12 },
    sentiment_pct: { pos: 0.37, neu: 0.42, neg: 0.21 },
    emotions_pct: { distress: 0.21, anger: 0.13, sadness: 0.15, calm: 0.51 },
    top_topics: [
      { key: "appointment_booking", pct: 0.24 },
      { key: "resource_request", pct: 0.19 },
      { key: "general_inquiry", pct: 0.16 },
    ],
    ewi: 0.38,
    anomalies: [],
  },
  Tabuk: {
    window: "last_60m",
    region: "Tabuk",
    counts: { events: 87, calls: 62, chats: 21, surveys: 4 },
    sentiment_pct: { pos: 0.45, neu: 0.39, neg: 0.16 },
    emotions_pct: { distress: 0.15, anger: 0.09, sadness: 0.11, calm: 0.65 },
    top_topics: [
      { key: "general_inquiry", pct: 0.31 },
      { key: "follow_up", pct: 0.18 },
      { key: "resource_request", pct: 0.14 },
    ],
    ewi: 0.31,
    anomalies: [],
  },
  Hail: {
    window: "last_60m",
    region: "Hail",
    counts: { events: 92, calls: 67, chats: 19, surveys: 6 },
    sentiment_pct: { pos: 0.48, neu: 0.37, neg: 0.15 },
    emotions_pct: { distress: 0.14, anger: 0.08, sadness: 0.1, calm: 0.68 },
    top_topics: [
      { key: "general_inquiry", pct: 0.29 },
      { key: "resource_request", pct: 0.21 },
      { key: "follow_up", pct: 0.15 },
    ],
    ewi: 0.29,
    anomalies: [],
  },
  "Northern Borders": {
    window: "last_60m",
    region: "Northern Borders",
    counts: { events: 64, calls: 47, chats: 14, surveys: 3 },
    sentiment_pct: { pos: 0.51, neu: 0.35, neg: 0.14 },
    emotions_pct: { distress: 0.12, anger: 0.07, sadness: 0.09, calm: 0.72 },
    top_topics: [
      { key: "general_inquiry", pct: 0.34 },
      { key: "follow_up", pct: 0.19 },
      { key: "resource_request", pct: 0.16 },
    ],
    ewi: 0.27,
    anomalies: [],
  },
  Jazan: {
    window: "last_60m",
    region: "Jazan",
    counts: { events: 165, calls: 118, chats: 39, surveys: 8 },
    sentiment_pct: { pos: 0.36, neu: 0.41, neg: 0.23 },
    emotions_pct: { distress: 0.22, anger: 0.12, sadness: 0.13, calm: 0.53 },
    top_topics: [
      { key: "appointment_booking", pct: 0.25 },
      { key: "general_inquiry", pct: 0.2 },
      { key: "wait_times", pct: 0.16 },
    ],
    ewi: 0.4,
    anomalies: [],
  },
  Najran: {
    window: "last_60m",
    region: "Najran",
    counts: { events: 121, calls: 84, chats: 31, surveys: 6 },
    sentiment_pct: { pos: 0.42, neu: 0.39, neg: 0.19 },
    emotions_pct: { distress: 0.17, anger: 0.1, sadness: 0.12, calm: 0.61 },
    top_topics: [
      { key: "general_inquiry", pct: 0.27 },
      { key: "resource_request", pct: 0.22 },
      { key: "follow_up", pct: 0.14 },
    ],
    ewi: 0.36,
    anomalies: [],
  },
  "Al-Bahah": {
    window: "last_60m",
    region: "Al-Bahah",
    counts: { events: 98, calls: 71, chats: 22, surveys: 5 },
    sentiment_pct: { pos: 0.44, neu: 0.38, neg: 0.18 },
    emotions_pct: { distress: 0.16, anger: 0.09, sadness: 0.11, calm: 0.64 },
    top_topics: [
      { key: "general_inquiry", pct: 0.3 },
      { key: "follow_up", pct: 0.21 },
      { key: "resource_request", pct: 0.17 },
    ],
    ewi: 0.33,
    anomalies: [],
  },
  "Al-Jouf": {
    window: "last_60m",
    region: "Al-Jouf",
    counts: { events: 76, calls: 54, chats: 18, surveys: 4 },
    sentiment_pct: { pos: 0.49, neu: 0.36, neg: 0.15 },
    emotions_pct: { distress: 0.13, anger: 0.08, sadness: 0.1, calm: 0.69 },
    top_topics: [
      { key: "general_inquiry", pct: 0.32 },
      { key: "resource_request", pct: 0.23 },
      { key: "follow_up", pct: 0.16 },
    ],
    ewi: 0.28,
    anomalies: [],
  },
};